### ISSUE TITLE
二维码登录失败

### ISSUE THREAD

**Issue by brahmachen** [McLemore/qqrobot#1]
`
[Wed Dec 27 2017 17:14:20 GMT+0800 (中国标准时间)] INFO 登录 step1 等待二维码校验结果

[Wed Dec 27 2017 17:14:21 GMT+0800 (中国标准时间)] INFO 登录 step1 等待二维码校验结果

[Wed Dec 27 2017 17:14:21 GMT+0800 (中国标准时间)] INFO 登录 step2 cookie 获取 ptwebqq

[Wed Dec 27 2017 17:14:21 GMT+0800 (中国标准时间)] INFO 登录 step3 获取 vfwebqq

[Wed Dec 27 2017 17:14:22 GMT+0800 (中国标准时间)] INFO 登录失败

[Wed Dec 27 2017 17:14:22 GMT+0800 (中国标准时间)] ERROR { retcode: 100000 }

`

**Comment by McLemore** [comment]
已经修复，按如下步骤重试
1. `sudo cnpm uninstall smartqq-bot -g`  
2. `sudo cnpm install qqrobot -g`  
3. `qqbot`
